### ISSUE TITLE
Markers And Bouncing Task List

### ISSUE THREAD

**Issue by rev007** [rev007/My-Neighborhood#1]
### TODOs
*Markers need to behave based on context (i.e. to catch your eye):*

- [ ] A marker shouldn't bounce when you tap it directly.
- [ ] A marker should bounce when clicked in the search list.
- [ ] A bouncing marker should stop bouncing when any action is performed on it or related to it.
