### ISSUE TITLE
New Marker Task List

### ISSUE THREAD

**Issue by rev007** [rev007/My-Neighborhood#2]
### TODOs
*New markers need the following abilities:*

- [ ] Simulate adding an image to the marker.
- [ ] Save a marker after information is added.
- [ ] Remove a marker if it is no longer needed.
